package com.amerbcs.sobacklog.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Delivery Core")
@org.kie.api.definition.type.Description("Delivery Core")
public class DeliveryCore implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Sales Document Line")
	private java.lang.String p0;
	@org.kie.api.definition.type.Label(value = "Schedule Line No")
	private java.lang.String p1;
	@org.kie.api.definition.type.Label(value = "Delivery No")
	private java.lang.String deliveryNo;
	@org.kie.api.definition.type.Label(value = "Delivery Item")
	private java.lang.String deliveryItem;
	@org.kie.api.definition.type.Label(value = "Delivery Quantity")
	private double deliveryQty;
	@org.kie.api.definition.type.Label(value = "Shipped Qty")
	private double shippedQty;
	@org.kie.api.definition.type.Label(value = "Created On")
	private java.lang.String createOn;
	@org.kie.api.definition.type.Label(value = "Delivery Block")
	private java.lang.String delvBlock;
	@org.kie.api.definition.type.Label(value = "Delivery DPC Status")
	private java.lang.String delvDPCStatus;
	@org.kie.api.definition.type.Label(value = "Delivery Status")
	private java.lang.String delvStatus;
	@org.kie.api.definition.type.Label(value = "Delivery Credit Status")
	private java.lang.String delvCreditStatus;
	@org.kie.api.definition.type.Label(value = "Delivery Credit Block")
	private boolean delvCreditBlock;

	public DeliveryCore() {
	}

	public java.lang.String getP0() {
		return this.p0;
	}

	public void setP0(java.lang.String p0) {
		this.p0 = p0;
	}

	public java.lang.String getP1() {
		return this.p1;
	}

	public void setP1(java.lang.String p1) {
		this.p1 = p1;
	}

	public java.lang.String getDeliveryNo() {
		return this.deliveryNo;
	}

	public void setDeliveryNo(java.lang.String deliveryNo) {
		this.deliveryNo = deliveryNo;
	}

	public java.lang.String getDeliveryItem() {
		return this.deliveryItem;
	}

	public void setDeliveryItem(java.lang.String deliveryItem) {
		this.deliveryItem = deliveryItem;
	}

	public double getDeliveryQty() {
		return this.deliveryQty;
	}

	public void setDeliveryQty(double deliveryQty) {
		this.deliveryQty = deliveryQty;
	}

	public double getShippedQty() {
		return this.shippedQty;
	}

	public void setShippedQty(double shippedQty) {
		this.shippedQty = shippedQty;
	}

	public java.lang.String getCreateOn() {
		return this.createOn;
	}

	public void setCreateOn(java.lang.String createOn) {
		this.createOn = createOn;
	}

	public java.lang.String getDelvBlock() {
		return this.delvBlock;
	}

	public void setDelvBlock(java.lang.String delvBlock) {
		this.delvBlock = delvBlock;
	}

	public java.lang.String getDelvDPCStatus() {
		return this.delvDPCStatus;
	}

	public void setDelvDPCStatus(java.lang.String delvDPCStatus) {
		this.delvDPCStatus = delvDPCStatus;
	}

	public java.lang.String getDelvStatus() {
		return this.delvStatus;
	}

	public void setDelvStatus(java.lang.String delvStatus) {
		this.delvStatus = delvStatus;
	}

	public java.lang.String getDelvCreditStatus() {
		return this.delvCreditStatus;
	}

	public void setDelvCreditStatus(java.lang.String delvCreditStatus) {
		this.delvCreditStatus = delvCreditStatus;
	}

	public boolean isDelvCreditBlock() {
		return this.delvCreditBlock;
	}

	public void setDelvCreditBlock(boolean delvCreditBlock) {
		this.delvCreditBlock = delvCreditBlock;
	}

	public DeliveryCore(java.lang.String p0, java.lang.String p1,
			java.lang.String deliveryNo, java.lang.String deliveryItem,
			double deliveryQty, double shippedQty, java.lang.String createOn,
			java.lang.String delvBlock, java.lang.String delvDPCStatus,
			java.lang.String delvStatus, java.lang.String delvCreditStatus,
			boolean delvCreditBlock) {
		this.p0 = p0;
		this.p1 = p1;
		this.deliveryNo = deliveryNo;
		this.deliveryItem = deliveryItem;
		this.deliveryQty = deliveryQty;
		this.shippedQty = shippedQty;
		this.createOn = createOn;
		this.delvBlock = delvBlock;
		this.delvDPCStatus = delvDPCStatus;
		this.delvStatus = delvStatus;
		this.delvCreditStatus = delvCreditStatus;
		this.delvCreditBlock = delvCreditBlock;
	}

}