package com.amerbcs.sobacklog.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EmailAction implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "To Email IDs")
	private java.util.List<java.lang.String> to;
	@org.kie.api.definition.type.Label(value = "Subject")
	private java.lang.String subject;
	@org.kie.api.definition.type.Label(value = "Body")
	private java.lang.String body;

	public EmailAction() {
	}

	public java.util.List<java.lang.String> getTo() {
		return this.to;
	}

	public void setTo(java.util.List<java.lang.String> to) {
		this.to = to;
	}

	public java.lang.String getSubject() {
		return this.subject;
	}

	public void setSubject(java.lang.String subject) {
		this.subject = subject;
	}

	public java.lang.String getBody() {
		return this.body;
	}

	public void setBody(java.lang.String body) {
		this.body = body;
	}

	public EmailAction(java.util.List<java.lang.String> to,
			java.lang.String subject, java.lang.String body) {
		this.to = to;
		this.subject = subject;
		this.body = body;
	}

}