package com.amerbcs.sobacklog.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Forecast And Buffer")
@org.kie.api.definition.type.Description("Forecast And Buffer")
public class ForecastAndBuffer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Forecast Indicator")
	private java.lang.String forecastIndicator;
	@org.kie.api.definition.type.Label(value = "Forecast Container")
	private java.lang.String forecastContainer;
	@org.kie.api.definition.type.Label(value = "Forecast Container Line")
	private java.lang.String forecastContainerLine;
	@org.kie.api.definition.type.Label(value = "Buffer Indicator")
	private java.lang.String bufferIndicator;
	@org.kie.api.definition.type.Label(value = "Buffer Container")
	private java.lang.String bufferContainer;
	@org.kie.api.definition.type.Label(value = "Buffer Container Line")
	private java.lang.String bufferContainerLine;
	@org.kie.api.definition.type.Label(value = "Buffer Type")
	private java.lang.String bufferType;
	@org.kie.api.definition.type.Label(value = "Buffer Type Text")
	private java.lang.String bufferTypeText;
	@org.kie.api.definition.type.Label(value = "Buffer Sub Type")
	private java.lang.String bufferSubType;
	@org.kie.api.definition.type.Label(value = "Buffer Sub Type Text")
	private java.lang.String bufferSubTypeText;
	@org.kie.api.definition.type.Label(value = "Active Flag")
	private boolean activeFlag;
	@org.kie.api.definition.type.Label(value = "Priority Flag")
	private boolean priorityFlag;

	public ForecastAndBuffer() {
	}

	public java.lang.String getForecastIndicator() {
		return this.forecastIndicator;
	}

	public void setForecastIndicator(java.lang.String forecastIndicator) {
		this.forecastIndicator = forecastIndicator;
	}

	public java.lang.String getForecastContainer() {
		return this.forecastContainer;
	}

	public void setForecastContainer(java.lang.String forecastContainer) {
		this.forecastContainer = forecastContainer;
	}

	public java.lang.String getForecastContainerLine() {
		return this.forecastContainerLine;
	}

	public void setForecastContainerLine(java.lang.String forecastContainerLine) {
		this.forecastContainerLine = forecastContainerLine;
	}

	public java.lang.String getBufferIndicator() {
		return this.bufferIndicator;
	}

	public void setBufferIndicator(java.lang.String bufferIndicator) {
		this.bufferIndicator = bufferIndicator;
	}

	public java.lang.String getBufferContainer() {
		return this.bufferContainer;
	}

	public void setBufferContainer(java.lang.String bufferContainer) {
		this.bufferContainer = bufferContainer;
	}

	public java.lang.String getBufferContainerLine() {
		return this.bufferContainerLine;
	}

	public void setBufferContainerLine(java.lang.String bufferContainerLine) {
		this.bufferContainerLine = bufferContainerLine;
	}

	public java.lang.String getBufferType() {
		return this.bufferType;
	}

	public void setBufferType(java.lang.String bufferType) {
		this.bufferType = bufferType;
	}

	public java.lang.String getBufferTypeText() {
		return this.bufferTypeText;
	}

	public void setBufferTypeText(java.lang.String bufferTypeText) {
		this.bufferTypeText = bufferTypeText;
	}

	public java.lang.String getBufferSubType() {
		return this.bufferSubType;
	}

	public void setBufferSubType(java.lang.String bufferSubType) {
		this.bufferSubType = bufferSubType;
	}

	public java.lang.String getBufferSubTypeText() {
		return this.bufferSubTypeText;
	}

	public void setBufferSubTypeText(java.lang.String bufferSubTypeText) {
		this.bufferSubTypeText = bufferSubTypeText;
	}

	public boolean isActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(boolean activeFlag) {
		this.activeFlag = activeFlag;
	}

	public boolean isPriorityFlag() {
		return this.priorityFlag;
	}

	public void setPriorityFlag(boolean priorityFlag) {
		this.priorityFlag = priorityFlag;
	}

	public ForecastAndBuffer(java.lang.String forecastIndicator,
			java.lang.String forecastContainer,
			java.lang.String forecastContainerLine,
			java.lang.String bufferIndicator, java.lang.String bufferContainer,
			java.lang.String bufferContainerLine, java.lang.String bufferType,
			java.lang.String bufferTypeText, java.lang.String bufferSubType,
			java.lang.String bufferSubTypeText, boolean activeFlag,
			boolean priorityFlag) {
		this.forecastIndicator = forecastIndicator;
		this.forecastContainer = forecastContainer;
		this.forecastContainerLine = forecastContainerLine;
		this.bufferIndicator = bufferIndicator;
		this.bufferContainer = bufferContainer;
		this.bufferContainerLine = bufferContainerLine;
		this.bufferType = bufferType;
		this.bufferTypeText = bufferTypeText;
		this.bufferSubType = bufferSubType;
		this.bufferSubTypeText = bufferSubTypeText;
		this.activeFlag = activeFlag;
		this.priorityFlag = priorityFlag;
	}

}