package com.amerbcs.sobacklog.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Sales Item")
@org.kie.api.definition.type.Description("Sales Item")
public class SalesItem implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("ID")
	private java.lang.String id;
	@org.kie.api.definition.type.Label("Sales Order No")
	private java.lang.String pk;
	@org.kie.api.definition.type.Label(value = "Core")
	private com.amerbcs.sobacklog.model.SalesItemCore core;

	@org.kie.api.definition.type.Label(value = "SChedules")
	private java.util.List<com.amerbcs.sobacklog.model.Schedules> schedules;

	public SalesItem() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getPk() {
		return this.pk;
	}

	public void setPk(java.lang.String pk) {
		this.pk = pk;
	}

	public com.amerbcs.sobacklog.model.SalesItemCore getCore() {
		return this.core;
	}

	public void setCore(com.amerbcs.sobacklog.model.SalesItemCore core) {
		this.core = core;
	}

	public java.util.List<com.amerbcs.sobacklog.model.Schedules> getSchedules() {
		return this.schedules;
	}

	public void setSchedules(
			java.util.List<com.amerbcs.sobacklog.model.Schedules> schedules) {
		this.schedules = schedules;
	}

	public SalesItem(java.lang.String id, java.lang.String pk,
			com.amerbcs.sobacklog.model.SalesItemCore core,
			java.util.List<com.amerbcs.sobacklog.model.Schedules> schedules) {
		this.id = id;
		this.pk = pk;
		this.core = core;
		this.schedules = schedules;
	}

}