package com.amerbcs.sobacklog.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Schedules")
@org.kie.api.definition.type.Description("Schedules")
public class Schedules implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Schedule Core")
	private com.amerbcs.sobacklog.model.ScheduleCore core;
	@org.kie.api.definition.type.Label(value = "Deliveries")
	private java.util.List<com.amerbcs.sobacklog.model.Deliveries> deliveries;

	public Schedules() {
	}

	public com.amerbcs.sobacklog.model.ScheduleCore getCore() {
		return this.core;
	}

	public void setCore(com.amerbcs.sobacklog.model.ScheduleCore core) {
		this.core = core;
	}

	public java.util.List<com.amerbcs.sobacklog.model.Deliveries> getDeliveries() {
		return this.deliveries;
	}

	public void setDeliveries(
			java.util.List<com.amerbcs.sobacklog.model.Deliveries> deliveries) {
		this.deliveries = deliveries;
	}

	public Schedules(com.amerbcs.sobacklog.model.ScheduleCore core,
			java.util.List<com.amerbcs.sobacklog.model.Deliveries> deliveries) {
		this.core = core;
		this.deliveries = deliveries;
	}

}