package com.amerbcs.sobacklog.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Schedule Core")
@org.kie.api.definition.type.Description("Schedule Core")
public class ScheduleCore implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Sales Document Line")
	private java.lang.String p0;
	@org.kie.api.definition.type.Label(value = "Schedule Line No")
	private java.lang.String scheduleLineNo;
	@org.kie.api.definition.type.Label(value = "Order Quantity")
	private double orderQty;
	@org.kie.api.definition.type.Label(value = "Confirm Quantity")
	private double confirmQty;
	@org.kie.api.definition.type.Label(value = "Delivery Quantity")
	private double deliveryQty;
	@org.kie.api.definition.type.Label(value = "Requirement Quantity")
	private double requirementQty;
	@org.kie.api.definition.type.Label(value = "Shipped Quantity")
	private double shippedQty;
	@org.kie.api.definition.type.Label(value = "Open Quantity")
	private double openQty;
	@org.kie.api.definition.type.Label(value = "Open Delivery Quantity")
	private double openDeliveryQty;
	@org.kie.api.definition.type.Label(value = "Requirement Type")
	private java.lang.String requirementType;
	@org.kie.api.definition.type.Label(value = "Customer Requirement Date")
	private java.lang.String customerReqDate;
	@org.kie.api.definition.type.Label(value = "ATP Date")
	private java.lang.String ATPDate;
	@org.kie.api.definition.type.Label(value = "Last Confirm Date")
	private java.lang.String lastConfirmDate;
	@org.kie.api.definition.type.Label(value = "Material Availability Date")
	private java.lang.String materialAvailDate;
	@org.kie.api.definition.type.Label(value = "CRD ATP Difference")
	private double crdatpDifference;
	@org.kie.api.definition.type.Label(value = "Schedule Block")
	private java.lang.String block;

	public ScheduleCore() {
	}

	public java.lang.String getP0() {
		return this.p0;
	}

	public void setP0(java.lang.String p0) {
		this.p0 = p0;
	}

	public java.lang.String getScheduleLineNo() {
		return this.scheduleLineNo;
	}

	public void setScheduleLineNo(java.lang.String scheduleLineNo) {
		this.scheduleLineNo = scheduleLineNo;
	}

	public double getOrderQty() {
		return this.orderQty;
	}

	public void setOrderQty(double orderQty) {
		this.orderQty = orderQty;
	}

	public double getConfirmQty() {
		return this.confirmQty;
	}

	public void setConfirmQty(double confirmQty) {
		this.confirmQty = confirmQty;
	}

	public double getDeliveryQty() {
		return this.deliveryQty;
	}

	public void setDeliveryQty(double deliveryQty) {
		this.deliveryQty = deliveryQty;
	}

	public double getRequirementQty() {
		return this.requirementQty;
	}

	public void setRequirementQty(double requirementQty) {
		this.requirementQty = requirementQty;
	}

	public double getShippedQty() {
		return this.shippedQty;
	}

	public void setShippedQty(double shippedQty) {
		this.shippedQty = shippedQty;
	}

	public double getOpenQty() {
		return this.openQty;
	}

	public void setOpenQty(double openQty) {
		this.openQty = openQty;
	}

	public double getOpenDeliveryQty() {
		return this.openDeliveryQty;
	}

	public void setOpenDeliveryQty(double openDeliveryQty) {
		this.openDeliveryQty = openDeliveryQty;
	}

	public java.lang.String getRequirementType() {
		return this.requirementType;
	}

	public void setRequirementType(java.lang.String requirementType) {
		this.requirementType = requirementType;
	}

	public java.lang.String getCustomerReqDate() {
		return this.customerReqDate;
	}

	public void setCustomerReqDate(java.lang.String customerReqDate) {
		this.customerReqDate = customerReqDate;
	}

	public java.lang.String getATPDate() {
		return this.ATPDate;
	}

	public void setATPDate(java.lang.String ATPDate) {
		this.ATPDate = ATPDate;
	}

	public java.lang.String getLastConfirmDate() {
		return this.lastConfirmDate;
	}

	public void setLastConfirmDate(java.lang.String lastConfirmDate) {
		this.lastConfirmDate = lastConfirmDate;
	}

	public java.lang.String getMaterialAvailDate() {
		return this.materialAvailDate;
	}

	public void setMaterialAvailDate(java.lang.String materialAvailDate) {
		this.materialAvailDate = materialAvailDate;
	}

	public double getCrdatpDifference() {
		return this.crdatpDifference;
	}

	public void setCrdatpDifference(double crdatpDifference) {
		this.crdatpDifference = crdatpDifference;
	}

	public java.lang.String getBlock() {
		return this.block;
	}

	public void setBlock(java.lang.String block) {
		this.block = block;
	}

	public ScheduleCore(java.lang.String p0, java.lang.String scheduleLineNo,
			double orderQty, double confirmQty, double deliveryQty,
			double requirementQty, double shippedQty, double openQty,
			double openDeliveryQty, java.lang.String requirementType,
			java.lang.String customerReqDate, java.lang.String ATPDate,
			java.lang.String lastConfirmDate,
			java.lang.String materialAvailDate, double crdatpDifference,
			java.lang.String block) {
		this.p0 = p0;
		this.scheduleLineNo = scheduleLineNo;
		this.orderQty = orderQty;
		this.confirmQty = confirmQty;
		this.deliveryQty = deliveryQty;
		this.requirementQty = requirementQty;
		this.shippedQty = shippedQty;
		this.openQty = openQty;
		this.openDeliveryQty = openDeliveryQty;
		this.requirementType = requirementType;
		this.customerReqDate = customerReqDate;
		this.ATPDate = ATPDate;
		this.lastConfirmDate = lastConfirmDate;
		this.materialAvailDate = materialAvailDate;
		this.crdatpDifference = crdatpDifference;
		this.block = block;
	}

}