package com.amerbcs.sobacklog.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TimeBound implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Time Bound Flag")
	private boolean flag;
	@org.kie.api.definition.type.Label(value = "Cosmos Query")
	private java.lang.String cosmosQuery;

	public TimeBound() {
	}

	public boolean isFlag() {
		return this.flag;
	}

	public void setFlag(boolean flag) {
		this.flag = flag;
	}

	public java.lang.String getCosmosQuery() {
		return this.cosmosQuery;
	}

	public void setCosmosQuery(java.lang.String cosmosQuery) {
		this.cosmosQuery = cosmosQuery;
	}

	public TimeBound(boolean flag, java.lang.String cosmosQuery) {
		this.flag = flag;
		this.cosmosQuery = cosmosQuery;
	}

}