package com.amerbcs.sobacklog.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Dates")
@org.kie.api.definition.type.Description("Dates")
public class Dates implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Customer Required Date")
	private java.lang.String customerReqDate;
	@org.kie.api.definition.type.Label(value = "Customer Required Date Previous Value")
	private java.lang.String customerReqDate_pvl;
	@org.kie.api.definition.type.Label(value = "Customer Required Date Difference")
	private double customerReqDate_dif;
	@org.kie.api.definition.type.Label(value = "Customer Required Date Change Time")
	private java.lang.String customerReqDate_tim;
	@org.kie.api.definition.type.Label(value = "Customer Requried Date Change User")
	private java.lang.String customerReqDate_usr;
	@org.kie.api.definition.type.Label(value = "ATP Date")
	private java.lang.String ATPDate;
	@org.kie.api.definition.type.Label(value = "ATP Date Previous Value")
	private java.lang.String ATPDate_pvl;
	@org.kie.api.definition.type.Label(value = "ATP Date Change Difference")
	private double ATPDate_dif;
	@org.kie.api.definition.type.Label(value = "ATP Date Change Date Time")
	private java.lang.String ATPDate_tim;
	@org.kie.api.definition.type.Label(value = "ATP Date Change User")
	private java.lang.String ATPDate_usr;
	@org.kie.api.definition.type.Label(value = "Multiple ATP Date")
	private boolean multipleATPDate;
	@org.kie.api.definition.type.Label(value = "Last Confirm Date")
	private java.lang.String lastConfirmDate;
	@org.kie.api.definition.type.Label(value = "Multiple Confirm Date")
	private boolean multipleConfirmDate;
	@org.kie.api.definition.type.Label(value = "Created Date ATP Difference")
	private double crdatpDifference;
	@org.kie.api.definition.type.Label(value = "Contract Start Date")
	private java.lang.String contractStartDate;
	@org.kie.api.definition.type.Label(value = "Contract End Date")
	private java.lang.String contractEndDate;

	public Dates() {
	}

	public java.lang.String getCustomerReqDate() {
		return this.customerReqDate;
	}

	public void setCustomerReqDate(java.lang.String customerReqDate) {
		this.customerReqDate = customerReqDate;
	}

	public java.lang.String getCustomerReqDate_pvl() {
		return this.customerReqDate_pvl;
	}

	public void setCustomerReqDate_pvl(java.lang.String customerReqDate_pvl) {
		this.customerReqDate_pvl = customerReqDate_pvl;
	}

	public double getCustomerReqDate_dif() {
		return this.customerReqDate_dif;
	}

	public void setCustomerReqDate_dif(double customerReqDate_dif) {
		this.customerReqDate_dif = customerReqDate_dif;
	}

	public java.lang.String getCustomerReqDate_tim() {
		return this.customerReqDate_tim;
	}

	public void setCustomerReqDate_tim(java.lang.String customerReqDate_tim) {
		this.customerReqDate_tim = customerReqDate_tim;
	}

	public java.lang.String getCustomerReqDate_usr() {
		return this.customerReqDate_usr;
	}

	public void setCustomerReqDate_usr(java.lang.String customerReqDate_usr) {
		this.customerReqDate_usr = customerReqDate_usr;
	}

	public java.lang.String getATPDate() {
		return this.ATPDate;
	}

	public void setATPDate(java.lang.String ATPDate) {
		this.ATPDate = ATPDate;
	}

	public java.lang.String getATPDate_pvl() {
		return this.ATPDate_pvl;
	}

	public void setATPDate_pvl(java.lang.String ATPDate_pvl) {
		this.ATPDate_pvl = ATPDate_pvl;
	}

	public double getATPDate_dif() {
		return this.ATPDate_dif;
	}

	public void setATPDate_dif(double ATPDate_dif) {
		this.ATPDate_dif = ATPDate_dif;
	}

	public java.lang.String getATPDate_tim() {
		return this.ATPDate_tim;
	}

	public void setATPDate_tim(java.lang.String ATPDate_tim) {
		this.ATPDate_tim = ATPDate_tim;
	}

	public java.lang.String getATPDate_usr() {
		return this.ATPDate_usr;
	}

	public void setATPDate_usr(java.lang.String ATPDate_usr) {
		this.ATPDate_usr = ATPDate_usr;
	}

	public boolean isMultipleATPDate() {
		return this.multipleATPDate;
	}

	public void setMultipleATPDate(boolean multipleATPDate) {
		this.multipleATPDate = multipleATPDate;
	}

	public java.lang.String getLastConfirmDate() {
		return this.lastConfirmDate;
	}

	public void setLastConfirmDate(java.lang.String lastConfirmDate) {
		this.lastConfirmDate = lastConfirmDate;
	}

	public boolean isMultipleConfirmDate() {
		return this.multipleConfirmDate;
	}

	public void setMultipleConfirmDate(boolean multipleConfirmDate) {
		this.multipleConfirmDate = multipleConfirmDate;
	}

	public double getCrdatpDifference() {
		return this.crdatpDifference;
	}

	public void setCrdatpDifference(double crdatpDifference) {
		this.crdatpDifference = crdatpDifference;
	}

	public java.lang.String getContractStartDate() {
		return this.contractStartDate;
	}

	public void setContractStartDate(java.lang.String contractStartDate) {
		this.contractStartDate = contractStartDate;
	}

	public java.lang.String getContractEndDate() {
		return this.contractEndDate;
	}

	public void setContractEndDate(java.lang.String contractEndDate) {
		this.contractEndDate = contractEndDate;
	}

	public Dates(java.lang.String customerReqDate,
			java.lang.String customerReqDate_pvl, double customerReqDate_dif,
			java.lang.String customerReqDate_tim,
			java.lang.String customerReqDate_usr, java.lang.String ATPDate,
			java.lang.String ATPDate_pvl, double ATPDate_dif,
			java.lang.String ATPDate_tim, java.lang.String ATPDate_usr,
			boolean multipleATPDate, java.lang.String lastConfirmDate,
			boolean multipleConfirmDate, double crdatpDifference,
			java.lang.String contractStartDate, java.lang.String contractEndDate) {
		this.customerReqDate = customerReqDate;
		this.customerReqDate_pvl = customerReqDate_pvl;
		this.customerReqDate_dif = customerReqDate_dif;
		this.customerReqDate_tim = customerReqDate_tim;
		this.customerReqDate_usr = customerReqDate_usr;
		this.ATPDate = ATPDate;
		this.ATPDate_pvl = ATPDate_pvl;
		this.ATPDate_dif = ATPDate_dif;
		this.ATPDate_tim = ATPDate_tim;
		this.ATPDate_usr = ATPDate_usr;
		this.multipleATPDate = multipleATPDate;
		this.lastConfirmDate = lastConfirmDate;
		this.multipleConfirmDate = multipleConfirmDate;
		this.crdatpDifference = crdatpDifference;
		this.contractStartDate = contractStartDate;
		this.contractEndDate = contractEndDate;
	}

}