package com.amerbcs.sobacklog.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Deliveries")
@org.kie.api.definition.type.Description("Deliveries")
public class Deliveries implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Delivery Core")
	private com.amerbcs.sobacklog.model.DeliveryCore core;

	public Deliveries() {
	}

	public com.amerbcs.sobacklog.model.DeliveryCore getCore() {
		return this.core;
	}

	public void setCore(com.amerbcs.sobacklog.model.DeliveryCore core) {
		this.core = core;
	}

	public Deliveries(com.amerbcs.sobacklog.model.DeliveryCore core) {
		this.core = core;
	}

}