package com.amerbcs.sobacklog.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Input implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Operation")
	private java.lang.String operation;
	@org.kie.api.definition.type.Label(value = "Old")
	private com.amerbcs.sobacklog.model.SalesItem old;
	@org.kie.api.definition.type.Label(value = "Current")
	private com.amerbcs.sobacklog.model.SalesItem current;

	public Input() {
	}

	public java.lang.String getOperation() {
		return this.operation;
	}

	public void setOperation(java.lang.String operation) {
		this.operation = operation;
	}

	public com.amerbcs.sobacklog.model.SalesItem getOld() {
		return this.old;
	}

	public void setOld(com.amerbcs.sobacklog.model.SalesItem old) {
		this.old = old;
	}

	public com.amerbcs.sobacklog.model.SalesItem getCurrent() {
		return this.current;
	}

	public void setCurrent(com.amerbcs.sobacklog.model.SalesItem current) {
		this.current = current;
	}

	public Input(java.lang.String operation,
			com.amerbcs.sobacklog.model.SalesItem old,
			com.amerbcs.sobacklog.model.SalesItem current) {
		this.operation = operation;
		this.old = old;
		this.current = current;
	}

}