package com.amerbcs.sobacklog.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Partners")
@org.kie.api.definition.type.Description("Partners")
public class Partners implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Partner Number")
	private java.lang.String no;
	@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "Type")
	private java.lang.String type;
	@org.kie.api.definition.type.Label(value = "Item Partner")
	private java.lang.String itemPartner;

	public Partners() {
	}

	public java.lang.String getNo() {
		return this.no;
	}

	public void setNo(java.lang.String no) {
		this.no = no;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getItemPartner() {
		return this.itemPartner;
	}

	public void setItemPartner(java.lang.String itemPartner) {
		this.itemPartner = itemPartner;
	}

	public Partners(java.lang.String no, java.lang.String name,
			java.lang.String type, java.lang.String itemPartner) {
		this.no = no;
		this.name = name;
		this.type = type;
		this.itemPartner = itemPartner;
	}

}