package com.amerbcs.sobacklog.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Pricing implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Net Value")
	private double netValue;
	@org.kie.api.definition.type.Label("Net Value Remaining")
	private double netValueRemaining;
	@org.kie.api.definition.type.Label("Unit Price")
	private double unitPrice;
	@org.kie.api.definition.type.Label("Extended Resale")
	private double extendedResale;

	@org.kie.api.definition.type.Label(value = "Material Pricing Group")
	private java.lang.String materialPricingGrp;

	@org.kie.api.definition.type.Label(value = "Final Sales Cost")
	private double finalSalesCost;

	@org.kie.api.definition.type.Label(value = "Calculated Cost")
	private double calculatedCost;

	@org.kie.api.definition.type.Label(value = "Material GP")
	private double materialGP;

	@org.kie.api.definition.type.Label(value = "Material GP Previous Value")
	private double materialGP_pvl;

	@org.kie.api.definition.type.Label(value = "Material GP Difference")
	private double materialGP_dif;

	@org.kie.api.definition.type.Label(value = "Material GP Change Time")
	private java.lang.String materialGP_tim;

	@org.kie.api.definition.type.Label(value = "Material GP Change User")
	private java.lang.String materialGP_usr;

	@org.kie.api.definition.type.Label(value = "Material GP Value")
	private double materialGPVal;

	@org.kie.api.definition.type.Label(value = "Resale Source")
	private java.lang.String resaleSource;

	@org.kie.api.definition.type.Label(value = "Cost Source")
	private java.lang.String costSource;

	@org.kie.api.definition.type.Label(value = "DC Cost")
	private double dcCost;

	@org.kie.api.definition.type.Label(value = "MPP Cost")
	private double mppCost;

	@org.kie.api.definition.type.Label(value = "Special Buy Cost")
	private double specialBuyCost;

	@org.kie.api.definition.type.Label(value = "Win sight Target")
	private double winsightTarget;

	@org.kie.api.definition.type.Label(value = "Winsight Floor")
	private double winsightFloor;

	@org.kie.api.definition.type.Label(value = "Tarrif Charge")
	private double tarrifCharge;

	@org.kie.api.definition.type.Label(value = "Pricing Unit")
	private int pricingUnit;

	@org.kie.api.definition.type.Label(value = "Cost Type")
	private java.lang.String costType;

	@org.kie.api.definition.type.Label(value = "Pricing Date")
	private java.lang.String pricingDate;

	public Pricing() {
	}

	public double getNetValue() {
		return this.netValue;
	}

	public void setNetValue(double netValue) {
		this.netValue = netValue;
	}

	public double getNetValueRemaining() {
		return this.netValueRemaining;
	}

	public void setNetValueRemaining(double netValueRemaining) {
		this.netValueRemaining = netValueRemaining;
	}

	public double getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(double unitPrice) {
		this.unitPrice = unitPrice;
	}

	public double getExtendedResale() {
		return this.extendedResale;
	}

	public void setExtendedResale(double extendedResale) {
		this.extendedResale = extendedResale;
	}

	public java.lang.String getMaterialPricingGrp() {
		return this.materialPricingGrp;
	}

	public void setMaterialPricingGrp(java.lang.String materialPricingGrp) {
		this.materialPricingGrp = materialPricingGrp;
	}

	public double getFinalSalesCost() {
		return this.finalSalesCost;
	}

	public void setFinalSalesCost(double finalSalesCost) {
		this.finalSalesCost = finalSalesCost;
	}

	public double getCalculatedCost() {
		return this.calculatedCost;
	}

	public void setCalculatedCost(double calculatedCost) {
		this.calculatedCost = calculatedCost;
	}

	public double getMaterialGP() {
		return this.materialGP;
	}

	public void setMaterialGP(double materialGP) {
		this.materialGP = materialGP;
	}

	public double getMaterialGP_pvl() {
		return this.materialGP_pvl;
	}

	public void setMaterialGP_pvl(double materialGP_pvl) {
		this.materialGP_pvl = materialGP_pvl;
	}

	public double getMaterialGP_dif() {
		return this.materialGP_dif;
	}

	public void setMaterialGP_dif(double materialGP_dif) {
		this.materialGP_dif = materialGP_dif;
	}

	public java.lang.String getMaterialGP_tim() {
		return this.materialGP_tim;
	}

	public void setMaterialGP_tim(java.lang.String materialGP_tim) {
		this.materialGP_tim = materialGP_tim;
	}

	public java.lang.String getMaterialGP_usr() {
		return this.materialGP_usr;
	}

	public void setMaterialGP_usr(java.lang.String materialGP_usr) {
		this.materialGP_usr = materialGP_usr;
	}

	public double getMaterialGPVal() {
		return this.materialGPVal;
	}

	public void setMaterialGPVal(double materialGPVal) {
		this.materialGPVal = materialGPVal;
	}

	public java.lang.String getResaleSource() {
		return this.resaleSource;
	}

	public void setResaleSource(java.lang.String resaleSource) {
		this.resaleSource = resaleSource;
	}

	public java.lang.String getCostSource() {
		return this.costSource;
	}

	public void setCostSource(java.lang.String costSource) {
		this.costSource = costSource;
	}

	public double getDcCost() {
		return this.dcCost;
	}

	public void setDcCost(double dcCost) {
		this.dcCost = dcCost;
	}

	public double getMppCost() {
		return this.mppCost;
	}

	public void setMppCost(double mppCost) {
		this.mppCost = mppCost;
	}

	public double getSpecialBuyCost() {
		return this.specialBuyCost;
	}

	public void setSpecialBuyCost(double specialBuyCost) {
		this.specialBuyCost = specialBuyCost;
	}

	public double getWinsightTarget() {
		return this.winsightTarget;
	}

	public void setWinsightTarget(double winsightTarget) {
		this.winsightTarget = winsightTarget;
	}

	public double getWinsightFloor() {
		return this.winsightFloor;
	}

	public void setWinsightFloor(double winsightFloor) {
		this.winsightFloor = winsightFloor;
	}

	public double getTarrifCharge() {
		return this.tarrifCharge;
	}

	public void setTarrifCharge(double tarrifCharge) {
		this.tarrifCharge = tarrifCharge;
	}

	public int getPricingUnit() {
		return this.pricingUnit;
	}

	public void setPricingUnit(int pricingUnit) {
		this.pricingUnit = pricingUnit;
	}

	public java.lang.String getCostType() {
		return this.costType;
	}

	public void setCostType(java.lang.String costType) {
		this.costType = costType;
	}

	public java.lang.String getPricingDate() {
		return this.pricingDate;
	}

	public void setPricingDate(java.lang.String pricingDate) {
		this.pricingDate = pricingDate;
	}

	public Pricing(double netValue, double netValueRemaining, double unitPrice,
			double extendedResale, java.lang.String materialPricingGrp,
			double finalSalesCost, double calculatedCost, double materialGP,
			double materialGP_pvl, double materialGP_dif,
			java.lang.String materialGP_tim, java.lang.String materialGP_usr,
			double materialGPVal, java.lang.String resaleSource,
			java.lang.String costSource, double dcCost, double mppCost,
			double specialBuyCost, double winsightTarget, double winsightFloor,
			double tarrifCharge, int pricingUnit, java.lang.String costType,
			java.lang.String pricingDate) {
		this.netValue = netValue;
		this.netValueRemaining = netValueRemaining;
		this.unitPrice = unitPrice;
		this.extendedResale = extendedResale;
		this.materialPricingGrp = materialPricingGrp;
		this.finalSalesCost = finalSalesCost;
		this.calculatedCost = calculatedCost;
		this.materialGP = materialGP;
		this.materialGP_pvl = materialGP_pvl;
		this.materialGP_dif = materialGP_dif;
		this.materialGP_tim = materialGP_tim;
		this.materialGP_usr = materialGP_usr;
		this.materialGPVal = materialGPVal;
		this.resaleSource = resaleSource;
		this.costSource = costSource;
		this.dcCost = dcCost;
		this.mppCost = mppCost;
		this.specialBuyCost = specialBuyCost;
		this.winsightTarget = winsightTarget;
		this.winsightFloor = winsightFloor;
		this.tarrifCharge = tarrifCharge;
		this.pricingUnit = pricingUnit;
		this.costType = costType;
		this.pricingDate = pricingDate;
	}

}